spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 123MASLO123
    database: postgres
    driverClassname: org.postgresql.Driver